import OpenAI from 'openai';
import type { 
  GenerateContentParameters, 
  GenerateContentResponse, 
  CountTokensParameters, 
  CountTokensResponse,
  EmbedContentParameters,
  EmbedContentResponse
} from '@google/genai';
import type { ContentGenerator } from './contentGenerator.js';
import type { UserTierId } from '../code_assist/types.js';
import type { LlmRole } from '../telemetry/llmRole.js';

export class OpenAiContentGenerator implements ContentGenerator {
  private openai: OpenAI;
  public userTier?: UserTierId;
  public userTierName?: string;

  constructor(baseUrl: string, apiKey: string) {
    this.openai = new OpenAI({ 
      baseURL: baseUrl, 
      apiKey: apiKey || 'dummy-local-key' 
    });
  }

  async generateContent(
    request: GenerateContentParameters,
    userPromptId: string,
    role: LlmRole,
  ): Promise<GenerateContentResponse> {
    const response = await this.openai.chat.completions.create({
      model: request.model || 'gemma-4-26b',
      messages: this.mapGeminiToOpenAI(request),
      temperature: request.config?.temperature,
      max_tokens: request.config?.maxOutputTokens,
      tools: this.scrubAndMapTools(request)
    });
    
    if (response.choices[0].message.tool_calls) {
      return await this.executeToolCall(request, response.choices[0].message, userPromptId, role);
    }
    
    return this.mapOpenAIToGemini(response);
  }

      async generateContentStream(
    request: GenerateContentParameters,
    userPromptId: string,
    role: LlmRole,
  ): Promise<AsyncGenerator<GenerateContentResponse>> {
    const self = this;
    async function* generator() {
      const response = await self.generateContent(request, userPromptId, role);
      yield response;
    }
    return generator();
  }

  async countTokens(request: CountTokensParameters): Promise<CountTokensResponse> {
    return { totalTokens: 0 };
  }

  async embedContent(request: EmbedContentParameters): Promise<EmbedContentResponse> {
    return { embeddings: [] };
  }

  private scrubAndMapTools(req: any): any[] {
    const outTools: any[] = [];
    const inTools = req.tools || (req.config && req.config.tools) || [];
    
    // Check existing tools for things like functionDeclarations
    if (Array.isArray(inTools)) {
      for (const tool of inTools) {
        if (tool.functionDeclarations) {
          for (const func of tool.functionDeclarations) {
            outTools.push({
              type: "function",
              function: {
                name: func.name,
                description: func.description || "",
                parameters: func.parametersJsonSchema || func.parameters || { type: "object", properties: {} }
              }
            });
          }
        }
      }
    }

    // Explicitly inject Tavily and Python code execution manually
    outTools.push({
      type: "function",
      function: {
        name: "tavily_search",
        description: "Search the web for real-time information. Returns a JSON string of search results.",
        parameters: {
          type: "object",
          properties: {
            query: { type: "string", description: "The search query" }
          },
          required: ["query"]
        }
      }
    });

    outTools.push({
      type: "function",
      function: {
        name: "execute_python_code",
        description: "Execute python code generated by the model. Returns execution output.",
        parameters: {
          type: "object",
          properties: {
            code: { type: "string", description: "The python code to execute" }
          },
          required: ["code"]
        }
      }
    });

    return outTools;
  }
  
  private async interceptFunctionCall(req: any, call: any): Promise<any> {
    const fs = require('fs');
    const { execSync } = require('child_process');
    const os = require('os');
    
    if (call.name === 'tavily_search') {
      const args = JSON.parse(call.arguments);
      const query = args.query;
      
      const quotaFile = os.homedir() + '/.gemini_cli_tavily_quota.json';
      let quota = { searches: 0 };
      if (fs.existsSync(quotaFile)) {
        try { quota = JSON.parse(fs.readFileSync(quotaFile, 'utf8')); } catch (e) {}
      }
      
      if (quota.searches >= 1000) {
        return JSON.stringify({ error: "Tavily search quota exceeded for this month." });
      }
      quota.searches += 1;
      fs.writeFileSync(quotaFile, JSON.stringify(quota));
      
      try {
        const resp = await fetch('https://api.tavily.com/search', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            api_key: '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',
            query: query,
            search_depth: "basic",
            include_answer: false,
            max_results: 3
          })
        });
        const data = await resp.json();
        return JSON.stringify(data);
      } catch (err: any) {
        return JSON.stringify({ error: err.message });
      }
    } 
    else if (call.name === 'execute_python_code') {
      const args = JSON.parse(call.arguments);
      try {
        const out = execSync(`python3 -c ${JSON.stringify(args.code)}`, { encoding: 'utf8', stdio: 'pipe' });
        return JSON.stringify({ output: out });
      } catch (err: any) {
        return JSON.stringify({ error: err.message, stderr: err.stderr });
      }
    }
    
    return JSON.stringify({ error: "Unsupported tool call" });
  }

  private async executeToolCall(req: GenerateContentParameters, responseMessage: any, userPromptId: string, role: string): Promise<GenerateContentResponse> {
    const call = responseMessage.tool_calls[0];
    const callId = call.id;
    const callResult = await this.interceptFunctionCall(req, call.function);
    
    const messages = this.mapGeminiToOpenAI(req);
    messages.push(responseMessage);
    messages.push({
      role: "tool",
      tool_call_id: callId,
      content: callResult
    });
    
    const response = await this.openai.chat.completions.create({
      model: req.model || 'gemma-4-26b',
      messages: messages,
      tools: this.scrubAndMapTools(req)
    });
    return this.mapOpenAIToGemini(response);
  }

    private mapGeminiToOpenAI(req: GenerateContentParameters): any[] {
    const messages: any[] = [];
    const anyReq = req as any;
    if (anyReq.systemInstruction?.parts) {
      messages.push({ role: 'system', content: anyReq.systemInstruction.parts.map((p: any) => p.text).join('\n') });
    }
    const contentsArray = Array.isArray(req.contents) ? req.contents : (req.contents ? [req.contents] : []);
    for (const c of contentsArray) {
      const anyC = c as any;
      messages.push({
        role: anyC.role === 'model' ? 'assistant' : anyC.role,
        content: Array.isArray(anyC.parts) ? anyC.parts.map((p: any) => p.text).join('\n') : ''
      });
    }
    return messages;
  }

  private mapOpenAIToGemini(resp: any): GenerateContentResponse {
    return {
      candidates: [{
        content: { parts: [{ text: resp.choices[0].message.content }], role: 'model' },
        finishReason: resp.choices[0].finish_reason,
      }],
      usageMetadata: {
        promptTokenCount: resp.usage?.prompt_tokens,
        candidatesTokenCount: resp.usage?.completion_tokens,
        totalTokenCount: resp.usage?.total_tokens
      }
    } as GenerateContentResponse;
  }
}
